-- 코드를 입력하세요

SELECT BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY , SUM(BOOK.PRICE * SALES.SALES)
FROM BOOK AS BOOK 

JOIN AUTHOR AS AUTHOR 
ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID 

JOIN BOOK_SALES AS SALES
ON BOOK.BOOK_ID = SALES.BOOK_ID

WHERE SUBSTRING(SALES_DATE,1,7) = '2022-01'

GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;
