-- 코드를 입력하세요
# SELECT A.CAR_ID, A.CAR_TYPE, TRUNCATE(A.DAILY_FEE * 30 * (1-C.DISCOUNT_RATE/100),0) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR AS A
# JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
# ON A.CAR_ID = B.CAR_ID
# JOIN (
#     SELECT CAR_TYPE, DISCOUNT_RATE 
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
#     WHERE DURATION_TYPE LIKE '%30%' 
#     AND (CAR_TYPE = '세단' 
#     OR CAR_TYPE = 'SUV')
# ) AS C
# ON A.CAR_TYPE = C.CAR_TYPE
# WHERE (B.END_DATE < '2022-11-01' OR B.START_DATE > '2022-11-30')
# AND (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV')
# GROUP BY A.CAR_ID
# HAVING (FEE>= 500000 AND FEE<2000000)
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC


SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID=H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE=P.CAR_TYPE
WHERE C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
) AND P.DURATION_TYPE='30일 이상'
GROUP BY C.CAR_ID
HAVING C.CAR_TYPE IN ('세단', 'SUV') AND (FEE>=500000 AND FEE<2000000) 
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC