-- 코드를 입력하세요
SELECT YEAR(SALE.SALES_DATE) AS YEAR, MONTH(SALE.SALES_DATE) AS MONTH, INFO.GENDER, COUNT(DISTINCT INFO.USER_ID) AS USERS
FROM USER_INFO AS INFO
JOIN ONLINE_SALE AS SALE
ON INFO.USER_ID = SALE.USER_ID
GROUP BY YEAR,MONTH,GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR,MONTH,GENDER