-- 코드를 입력하세요
SELECT 
    YEAR(B.SALES_DATE) AS YEAR, 
    MONTH(B.SALES_DATE) AS MONTH, 
    COUNT(DISTINCT A.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT A.USER_ID) / 
        (SELECT DISTINCT COUNT(*) FROM USER_INFO WHERE SUBSTRING(JOINED, 1, 4) = '2021'), 
        1
    ) AS RATIO
FROM 
    USER_INFO AS A
JOIN 
    ONLINE_SALE AS B ON A.USER_ID = B.USER_ID AND SUBSTRING(A.JOINED, 1, 4) = '2021'
GROUP BY 
    YEAR, MONTH
ORDER BY
    YEAR, MONTH

