-- 코드를 입력하세요
SELECT B.HISTORY_ID, 
TRUNCATE(SUM(A.DAILY_FEE * (DATEDIFF(B.END_DATE,B.START_DATE)+1) * (
    CASE 
    WHEN (DATEDIFF(B.END_DATE,B.START_DATE)+1) >= 90 THEN 0.85
    WHEN (DATEDIFF(B.END_DATE,B.START_DATE)+1) >= 30 THEN 0.92
    WHEN (DATEDIFF(B.END_DATE,B.START_DATE)+1) >= 7 THEN 0.95
    ELSE 1
    END
) ),0) AS FEE

FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B

ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = '트럭'
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC